// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_log.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :exec

INSERT INTO audit_log (tenant_id, event, payload)
VALUES ($1, $2, $3)
`

type CreateAuditLogParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Event    string      `json:"event"`
	Payload  []byte      `json:"payload"`
}

// Audit-log queries. The append-only log records each cycle event, including
// reserve snapshots, with a jsonb payload. Retention (180 days) is enforced by a
// scheduled purge, not here.
func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.Exec(ctx, createAuditLog, arg.TenantID, arg.Event, arg.Payload)
	return err
}

const listAuditLog = `-- name: ListAuditLog :many
SELECT id, tenant_id, event, payload, created_at
FROM audit_log
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListAuditLogParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Limit    int32       `json:"limit"`
}

func (q *Queries) ListAuditLog(ctx context.Context, arg ListAuditLogParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLog, arg.TenantID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Event,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
