// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customers.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCustomer = `-- name: CreateCustomer :one

INSERT INTO customers (tenant_id, external_ref, id_hash)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateCustomerParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	ExternalRef string      `json:"external_ref"`
	IDHash      string      `json:"id_hash"`
}

// Customer queries. id_hash is the Poseidon2 hash of external_ref, computed by
// the prover stack. The orchestrator only stores and reads it.
func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createCustomer, arg.TenantID, arg.ExternalRef, arg.IDHash)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
