// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cycle_runs.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimCycle = `-- name: ClaimCycle :one

INSERT INTO cycle_runs (tenant_id, request_key)
VALUES ($1, $2)
ON CONFLICT (tenant_id, request_key) DO NOTHING
RETURNING id
`

type ClaimCycleParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	RequestKey string      `json:"request_key"`
}

// Cycle idempotency claims. ClaimCycle inserts the request key; on a conflict
// (the key was already claimed) it returns no row, which the repo maps to a
// "duplicate" result rather than an error.
func (q *Queries) ClaimCycle(ctx context.Context, arg ClaimCycleParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, claimCycle, arg.TenantID, arg.RequestKey)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
