// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: liabilities.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLiability = `-- name: CreateLiability :exec

INSERT INTO liabilities (tenant_id, customer_id, balance)
VALUES ($1, $2, $3)
`

type CreateLiabilityParams struct {
	TenantID   pgtype.UUID    `json:"tenant_id"`
	CustomerID pgtype.UUID    `json:"customer_id"`
	Balance    pgtype.Numeric `json:"balance"`
}

// Liability queries. balance is integer minor units stored as numeric(38,0) for
// exactness. as_of defaults to now() at insert.
func (q *Queries) CreateLiability(ctx context.Context, arg CreateLiabilityParams) error {
	_, err := q.db.Exec(ctx, createLiability, arg.TenantID, arg.CustomerID, arg.Balance)
	return err
}

const listLiabilities = `-- name: ListLiabilities :many
SELECT l.id, l.customer_id, c.id_hash, l.balance, l.as_of
FROM liabilities l
JOIN customers c ON c.id = l.customer_id
WHERE l.tenant_id = $1
ORDER BY l.as_of
`

type ListLiabilitiesRow struct {
	ID         pgtype.UUID        `json:"id"`
	CustomerID pgtype.UUID        `json:"customer_id"`
	IDHash     string             `json:"id_hash"`
	Balance    pgtype.Numeric     `json:"balance"`
	AsOf       pgtype.Timestamptz `json:"as_of"`
}

// The tenant's current customer balances, joined to the customer id_hash the
// prover witnesses into the Merkle Sum Tree.
func (q *Queries) ListLiabilities(ctx context.Context, tenantID pgtype.UUID) ([]ListLiabilitiesRow, error) {
	rows, err := q.db.Query(ctx, listLiabilities, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLiabilitiesRow{}
	for rows.Next() {
		var i ListLiabilitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.IDHash,
			&i.Balance,
			&i.AsOf,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
