// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Event     string             `json:"event"`
	Payload   []byte             `json:"payload"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Customer struct {
	ID          pgtype.UUID `json:"id"`
	TenantID    pgtype.UUID `json:"tenant_id"`
	ExternalRef string      `json:"external_ref"`
	IDHash      string      `json:"id_hash"`
}

type CycleRun struct {
	ID         pgtype.UUID        `json:"id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	RequestKey string             `json:"request_key"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Liability struct {
	ID         pgtype.UUID        `json:"id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	CustomerID pgtype.UUID        `json:"customer_id"`
	Balance    pgtype.Numeric     `json:"balance"`
	AsOf       pgtype.Timestamptz `json:"as_of"`
}

type MerkleTree struct {
	ID         pgtype.UUID `json:"id"`
	ProofID    pgtype.UUID `json:"proof_id"`
	Depth      int32       `json:"depth"`
	Serialized []byte      `json:"serialized"`
}

type Proof struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	ChainProofID int64              `json:"chain_proof_id"`
	RootH        string             `json:"root_h"`
	R            pgtype.Numeric     `json:"r"`
	L            pgtype.Numeric     `json:"l"`
	Timestamp    pgtype.Timestamptz `json:"timestamp"`
	ProofBlob    []byte             `json:"proof_blob"`
}

type ReserveSource struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
	Type     string      `json:"type"`
	Config   []byte      `json:"config"`
}

type Tenant struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Plan      string             `json:"plan"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
