// Package repo holds the database adapters. Postgres uses pgx; the typed
// queries that back these methods are generated by sqlc from query/*.sql into
// this package. This file owns the pool, runs the transactions, and maps the
// generated pgtype rows to and from the domain entities (see convert.go).
package repo

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/jes-labs/solva/services/orchestrator/internal/entity"
	"github.com/jes-labs/solva/services/orchestrator/internal/usecase"
)

// ErrNotFound is returned when a lookup matches no row. Callers check it with
// errors.Is rather than reaching for the pgx-specific sentinel.
var ErrNotFound = errors.New("repo: not found")

// errNotImplemented marks a method that still waits on an upstream contract.
var errNotImplemented = errors.New("repo: not implemented")

// Postgres implements ProofRepo and ReserveRepo over a pgx pool.
type Postgres struct {
	pool *pgxpool.Pool
	q    *Queries
}

// NewPostgres opens the pool and pings once so a bad DSN fails at startup.
func NewPostgres(ctx context.Context, dsn string) (*Postgres, error) {
	pool, err := pgxpool.New(ctx, dsn)
	if err != nil {
		return nil, fmt.Errorf("open pgx pool: %w", err)
	}
	if err := pool.Ping(ctx); err != nil {
		pool.Close()
		return nil, fmt.Errorf("ping postgres: %w", err)
	}
	return &Postgres{pool: pool, q: New(pool)}, nil
}

// Close releases the pool.
func (p *Postgres) Close() {
	p.pool.Close()
}

// SaveProof writes the proof and its serialized tree in one transaction so the
// proofs row and the merkle_trees row stay consistent.
func (p *Postgres) SaveProof(ctx context.Context, proof entity.Proof, serializedTree []byte) error {
	tenantID, err := toUUID(proof.TenantID)
	if err != nil {
		return err
	}
	r, err := toNumeric(proof.ReservesTotal)
	if err != nil {
		return err
	}
	l, err := toNumeric(proof.LiabilitiesTotal)
	if err != nil {
		return err
	}

	tx, err := p.pool.Begin(ctx)
	if err != nil {
		return fmt.Errorf("begin tx: %w", err)
	}
	defer tx.Rollback(ctx) // no-op once the tx is committed

	qtx := p.q.WithTx(tx)

	id, err := qtx.CreateProof(ctx, CreateProofParams{
		TenantID:     tenantID,
		ChainProofID: int64(proof.ChainProofID),
		RootH:        proof.RootHash,
		R:            r,
		L:            l,
		ProofBlob:    proof.Blob,
	})
	if err != nil {
		return fmt.Errorf("insert proof: %w", err)
	}

	// depth is carried inside the serialized tree the prover produces. The
	// orchestrator stores that blob opaquely, so depth stays 0 until the
	// serialized-tree schema is defined (same dependency as GetInclusion).
	if err := qtx.CreateMerkleTree(ctx, CreateMerkleTreeParams{
		ProofID:    id,
		Depth:      0,
		Serialized: serializedTree,
	}); err != nil {
		return fmt.Errorf("insert merkle tree: %w", err)
	}

	if err := tx.Commit(ctx); err != nil {
		return fmt.Errorf("commit tx: %w", err)
	}
	return nil
}

// GetProof loads one proof by internal id.
func (p *Postgres) GetProof(ctx context.Context, id string) (entity.Proof, error) {
	pid, err := toUUID(id)
	if err != nil {
		return entity.Proof{}, err
	}
	row, err := p.q.GetProof(ctx, pid)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return entity.Proof{}, ErrNotFound
		}
		return entity.Proof{}, fmt.Errorf("get proof: %w", err)
	}
	return proofFromRow(row)
}

// GetLatestProof loads the most recent proof for a tenant.
func (p *Postgres) GetLatestProof(ctx context.Context, tenantID string) (entity.Proof, error) {
	tid, err := toUUID(tenantID)
	if err != nil {
		return entity.Proof{}, err
	}
	row, err := p.q.GetLatestProof(ctx, tid)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return entity.Proof{}, ErrNotFound
		}
		return entity.Proof{}, fmt.Errorf("get latest proof: %w", err)
	}
	return proofFromRow(row)
}

// GetInclusion builds an inclusion reference from the stored serialized tree.
func (p *Postgres) GetInclusion(ctx context.Context, ref string) (entity.InclusionRef, error) {
	_ = ctx
	_ = ref
	// Building an inclusion reference means decoding the prover's serialized
	// Merkle Sum Tree (merkle_trees.serialized) into sibling path nodes. That
	// format is owned by the prover and is not finalized, so this stays a stub
	// until the serialized-tree schema lands.
	return entity.InclusionRef{}, errNotImplemented
}

// LoadLiabilities loads a tenant's current customer balances for witnessing.
func (p *Postgres) LoadLiabilities(ctx context.Context, tenantID string) ([]usecase.Liability, error) {
	tid, err := toUUID(tenantID)
	if err != nil {
		return nil, err
	}
	rows, err := p.q.ListLiabilities(ctx, tid)
	if err != nil {
		return nil, fmt.Errorf("list liabilities: %w", err)
	}
	out := make([]usecase.Liability, 0, len(rows))
	for _, row := range rows {
		balance, err := fromNumeric(row.Balance)
		if err != nil {
			return nil, err
		}
		out = append(out, usecase.Liability{
			CustomerIDHash: row.IDHash,
			Balance:        balance,
		})
	}
	return out, nil
}

// SaveSnapshot records a reserve snapshot in the audit log for the next fraud
// bound and the cycle history. The schema has no dedicated snapshots table; the
// append-only audit_log is the home for these events.
func (p *Postgres) SaveSnapshot(ctx context.Context, snap entity.ReserveSnapshot) error {
	tid, err := toUUID(snap.TenantID)
	if err != nil {
		return err
	}
	payload, err := json.Marshal(snap)
	if err != nil {
		return fmt.Errorf("marshal snapshot: %w", err)
	}
	if err := p.q.CreateAuditLog(ctx, CreateAuditLogParams{
		TenantID: tid,
		Event:    "reserve_snapshot",
		Payload:  payload,
	}); err != nil {
		return fmt.Errorf("save snapshot: %w", err)
	}
	return nil
}

// LatestReserves returns the previous cycle's reserve total for the fraud bound.
func (p *Postgres) LatestReserves(ctx context.Context, tenantID string) (string, error) {
	tid, err := toUUID(tenantID)
	if err != nil {
		return "", err
	}
	n, err := p.q.GetLatestReservesTotal(ctx, tid)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			// No prior proof: there is no previous total to report. The first
			// cycle's fraud-bound exception is the use-case's concern, not ours.
			return "0", nil
		}
		return "", fmt.Errorf("latest reserves: %w", err)
	}
	return fromNumeric(n)
}

// ClaimCycle records the cycle's idempotency key. The INSERT ... ON CONFLICT DO
// NOTHING RETURNING returns a row when the key is new, and no row when it was
// already claimed. A missing row is the durable "duplicate" signal, not an error.
func (p *Postgres) ClaimCycle(ctx context.Context, tenantID, requestKey string) (bool, error) {
	tid, err := toUUID(tenantID)
	if err != nil {
		return false, err
	}
	if _, err := p.q.ClaimCycle(ctx, ClaimCycleParams{TenantID: tid, RequestKey: requestKey}); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return false, nil
		}
		return false, fmt.Errorf("claim cycle: %w", err)
	}
	return true, nil
}

// AppendAudit writes one event to the append-only audit log.
func (p *Postgres) AppendAudit(ctx context.Context, tenantID, event string, payload []byte) error {
	tid, err := toUUID(tenantID)
	if err != nil {
		return err
	}
	if err := p.q.CreateAuditLog(ctx, CreateAuditLogParams{
		TenantID: tid,
		Event:    event,
		Payload:  payload,
	}); err != nil {
		return fmt.Errorf("append audit: %w", err)
	}
	return nil
}

// proofFromRow maps a generated proofs row to the domain Proof, converting each
// pgtype value back to the string/time form the entity uses.
func proofFromRow(row Proof) (entity.Proof, error) {
	r, err := fromNumeric(row.R)
	if err != nil {
		return entity.Proof{}, err
	}
	l, err := fromNumeric(row.L)
	if err != nil {
		return entity.Proof{}, err
	}
	return entity.Proof{
		ID:               fromUUID(row.ID),
		TenantID:         fromUUID(row.TenantID),
		ChainProofID:     uint64(row.ChainProofID),
		RootHash:         row.RootH,
		ReservesTotal:    r,
		LiabilitiesTotal: l,
		Blob:             row.ProofBlob,
		PublishedAt:      row.Timestamp.Time,
	}, nil
}

// Ensure Postgres satisfies the repo ports.
var (
	_ usecase.ProofRepo   = (*Postgres)(nil)
	_ usecase.ReserveRepo = (*Postgres)(nil)
)
