// Package repo holds the database adapters. Postgres uses pgx; the typed
// queries that back these methods are generated by sqlc from query/*.sql into
// this package. The hand-written code here owns the pool and maps rows to
// entities; the SQL itself lives in the query files.
package repo

import (
	"context"
	"errors"
	"fmt"

	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/jes-labs/solva/services/orchestrator/internal/entity"
	"github.com/jes-labs/solva/services/orchestrator/internal/usecase"
)

// errNotImplemented marks a query that waits on the sqlc-generated code.
var errNotImplemented = errors.New("repo: query not implemented, generate with sqlc")

// Postgres implements ProofRepo and ReserveRepo over a pgx pool.
type Postgres struct {
	pool *pgxpool.Pool
}

// NewPostgres opens the pool and pings once so a bad DSN fails at startup.
func NewPostgres(ctx context.Context, dsn string) (*Postgres, error) {
	pool, err := pgxpool.New(ctx, dsn)
	if err != nil {
		return nil, fmt.Errorf("open pgx pool: %w", err)
	}
	if err := pool.Ping(ctx); err != nil {
		pool.Close()
		return nil, fmt.Errorf("ping postgres: %w", err)
	}
	return &Postgres{pool: pool}, nil
}

// Close releases the pool.
func (p *Postgres) Close() {
	p.pool.Close()
}

// SaveProof writes the proof and its serialized tree in one transaction so the
// proofs row and the merkle_trees row stay consistent.
func (p *Postgres) SaveProof(ctx context.Context, proof entity.Proof, serializedTree []byte) error {
	_ = ctx
	_ = proof
	_ = serializedTree
	// sqlc: queries.CreateProof then queries.CreateMerkleTree inside a tx.
	return errNotImplemented
}

// GetProof loads one proof by internal id.
func (p *Postgres) GetProof(ctx context.Context, id string) (entity.Proof, error) {
	_ = ctx
	_ = id
	// sqlc: queries.GetProof.
	return entity.Proof{}, errNotImplemented
}

// GetLatestProof loads the most recent proof for a tenant.
func (p *Postgres) GetLatestProof(ctx context.Context, tenantID string) (entity.Proof, error) {
	_ = ctx
	_ = tenantID
	// sqlc: queries.GetLatestProof.
	return entity.Proof{}, errNotImplemented
}

// GetInclusion builds an inclusion reference from the stored serialized tree.
// The path nodes are read from the tree the prover produced, not recomputed.
func (p *Postgres) GetInclusion(ctx context.Context, ref string) (entity.InclusionRef, error) {
	_ = ctx
	_ = ref
	// sqlc: queries.GetMerkleTreeByCustomerRef, then decode the path.
	return entity.InclusionRef{}, errNotImplemented
}

// LoadLiabilities loads a tenant's current customer balances for witnessing.
func (p *Postgres) LoadLiabilities(ctx context.Context, tenantID string) ([]usecase.Liability, error) {
	_ = ctx
	_ = tenantID
	// sqlc: queries.ListLiabilities.
	return nil, errNotImplemented
}

// SaveSnapshot records a reserve snapshot for audit and the next fraud bound.
func (p *Postgres) SaveSnapshot(ctx context.Context, snap entity.ReserveSnapshot) error {
	_ = ctx
	_ = snap
	// sqlc: queries.CreateReserveSnapshot.
	return errNotImplemented
}

// LatestReserves returns the previous cycle's reserve total for the fraud bound.
func (p *Postgres) LatestReserves(ctx context.Context, tenantID string) (string, error) {
	_ = ctx
	_ = tenantID
	// sqlc: queries.GetLatestReservesTotal.
	return "", errNotImplemented
}

// Ensure Postgres satisfies the repo ports.
var (
	_ usecase.ProofRepo   = (*Postgres)(nil)
	_ usecase.ReserveRepo = (*Postgres)(nil)
)
