// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: proofs.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMerkleTree = `-- name: CreateMerkleTree :exec
INSERT INTO merkle_trees (proof_id, depth, serialized)
VALUES ($1, $2, $3)
`

type CreateMerkleTreeParams struct {
	ProofID    pgtype.UUID `json:"proof_id"`
	Depth      int32       `json:"depth"`
	Serialized []byte      `json:"serialized"`
}

func (q *Queries) CreateMerkleTree(ctx context.Context, arg CreateMerkleTreeParams) error {
	_, err := q.db.Exec(ctx, createMerkleTree, arg.ProofID, arg.Depth, arg.Serialized)
	return err
}

const createProof = `-- name: CreateProof :one

INSERT INTO proofs (tenant_id, chain_proof_id, root_h, r, l, proof_blob)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type CreateProofParams struct {
	TenantID     pgtype.UUID    `json:"tenant_id"`
	ChainProofID int64          `json:"chain_proof_id"`
	RootH        string         `json:"root_h"`
	R            pgtype.Numeric `json:"r"`
	L            pgtype.Numeric `json:"l"`
	ProofBlob    []byte         `json:"proof_blob"`
}

// Proof and Merkle-tree queries. sqlc reads the schema from migrations/ and
// generates type-safe Go into internal/repo.
func (q *Queries) CreateProof(ctx context.Context, arg CreateProofParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createProof,
		arg.TenantID,
		arg.ChainProofID,
		arg.RootH,
		arg.R,
		arg.L,
		arg.ProofBlob,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getLatestProof = `-- name: GetLatestProof :one
SELECT id, tenant_id, chain_proof_id, root_h, r, l, "timestamp", proof_blob
FROM proofs
WHERE tenant_id = $1
ORDER BY "timestamp" DESC
LIMIT 1
`

func (q *Queries) GetLatestProof(ctx context.Context, tenantID pgtype.UUID) (Proof, error) {
	row := q.db.QueryRow(ctx, getLatestProof, tenantID)
	var i Proof
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChainProofID,
		&i.RootH,
		&i.R,
		&i.L,
		&i.Timestamp,
		&i.ProofBlob,
	)
	return i, err
}

const getLatestReservesTotal = `-- name: GetLatestReservesTotal :one
SELECT r
FROM proofs
WHERE tenant_id = $1
ORDER BY "timestamp" DESC
LIMIT 1
`

// The previous cycle's reserve total, which the fraud bound (R <= 1.1 * R_prev)
// needs. It is just the most recent proof's R for the tenant.
func (q *Queries) GetLatestReservesTotal(ctx context.Context, tenantID pgtype.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getLatestReservesTotal, tenantID)
	var r pgtype.Numeric
	err := row.Scan(&r)
	return r, err
}

const getMerkleTreeByProof = `-- name: GetMerkleTreeByProof :one
SELECT id, proof_id, depth, serialized
FROM merkle_trees
WHERE proof_id = $1
`

func (q *Queries) GetMerkleTreeByProof(ctx context.Context, proofID pgtype.UUID) (MerkleTree, error) {
	row := q.db.QueryRow(ctx, getMerkleTreeByProof, proofID)
	var i MerkleTree
	err := row.Scan(
		&i.ID,
		&i.ProofID,
		&i.Depth,
		&i.Serialized,
	)
	return i, err
}

const getProof = `-- name: GetProof :one
SELECT id, tenant_id, chain_proof_id, root_h, r, l, "timestamp", proof_blob
FROM proofs
WHERE id = $1
`

func (q *Queries) GetProof(ctx context.Context, id pgtype.UUID) (Proof, error) {
	row := q.db.QueryRow(ctx, getProof, id)
	var i Proof
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChainProofID,
		&i.RootH,
		&i.R,
		&i.L,
		&i.Timestamp,
		&i.ProofBlob,
	)
	return i, err
}
