// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Audit-log queries. The append-only log records each cycle event, including
	// reserve snapshots, with a jsonb payload. Retention (180 days) is enforced by a
	// scheduled purge, not here.
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error
	// Customer queries. id_hash is the Poseidon2 hash of external_ref, computed by
	// the prover stack. The orchestrator only stores and reads it.
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (pgtype.UUID, error)
	// Liability queries. balance is integer minor units stored as numeric(38,0) for
	// exactness. as_of defaults to now() at insert.
	CreateLiability(ctx context.Context, arg CreateLiabilityParams) error
	CreateMerkleTree(ctx context.Context, arg CreateMerkleTreeParams) error
	// Proof and Merkle-tree queries. sqlc reads the schema from migrations/ and
	// generates type-safe Go into internal/repo.
	CreateProof(ctx context.Context, arg CreateProofParams) (pgtype.UUID, error)
	// Tenant queries. The orchestrator does not own tenant creation in production
	// (that is the control plane), but the repo and tests need to insert one so the
	// foreign keys on proofs, customers, and liabilities resolve.
	CreateTenant(ctx context.Context, arg CreateTenantParams) (pgtype.UUID, error)
	GetLatestProof(ctx context.Context, tenantID pgtype.UUID) (Proof, error)
	// The previous cycle's reserve total, which the fraud bound (R <= 1.1 * R_prev)
	// needs. It is just the most recent proof's R for the tenant.
	GetLatestReservesTotal(ctx context.Context, tenantID pgtype.UUID) (pgtype.Numeric, error)
	GetMerkleTreeByProof(ctx context.Context, proofID pgtype.UUID) (MerkleTree, error)
	GetProof(ctx context.Context, id pgtype.UUID) (Proof, error)
	ListAuditLog(ctx context.Context, arg ListAuditLogParams) ([]AuditLog, error)
	// The tenant's current customer balances, joined to the customer id_hash the
	// prover witnesses into the Merkle Sum Tree.
	ListLiabilities(ctx context.Context, tenantID pgtype.UUID) ([]ListLiabilitiesRow, error)
}

var _ Querier = (*Queries)(nil)
