// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTenant = `-- name: CreateTenant :one

INSERT INTO tenants (name, plan)
VALUES ($1, $2)
RETURNING id
`

type CreateTenantParams struct {
	Name string `json:"name"`
	Plan string `json:"plan"`
}

// Tenant queries. The orchestrator does not own tenant creation in production
// (that is the control plane), but the repo and tests need to insert one so the
// foreign keys on proofs, customers, and liabilities resolve.
func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createTenant, arg.Name, arg.Plan)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getTenantContract = `-- name: GetTenantContract :one
SELECT contract_id, network
FROM tenants
WHERE id = $1
`

type GetTenantContractRow struct {
	ContractID pgtype.Text `json:"contract_id"`
	Network    string      `json:"network"`
}

func (q *Queries) GetTenantContract(ctx context.Context, id pgtype.UUID) (GetTenantContractRow, error) {
	row := q.db.QueryRow(ctx, getTenantContract, id)
	var i GetTenantContractRow
	err := row.Scan(&i.ContractID, &i.Network)
	return i, err
}

const setTenantContract = `-- name: SetTenantContract :exec
UPDATE tenants
SET contract_id = $2, network = $3
WHERE id = $1
`

type SetTenantContractParams struct {
	ID         pgtype.UUID `json:"id"`
	ContractID pgtype.Text `json:"contract_id"`
	Network    string      `json:"network"`
}

func (q *Queries) SetTenantContract(ctx context.Context, arg SetTenantContractParams) error {
	_, err := q.db.Exec(ctx, setTenantContract, arg.ID, arg.ContractID, arg.Network)
	return err
}
