// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTenant = `-- name: CreateTenant :one

INSERT INTO tenants (name, plan)
VALUES ($1, $2)
RETURNING id
`

type CreateTenantParams struct {
	Name string `json:"name"`
	Plan string `json:"plan"`
}

// Tenant queries. The orchestrator does not own tenant creation in production
// (that is the control plane), but the repo and tests need to insert one so the
// foreign keys on proofs, customers, and liabilities resolve.
func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createTenant, arg.Name, arg.Plan)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
