// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: prover.proto

package proverpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A single customer liability. The balance is a decimal string to avoid
// floating point. The prover converts it to a field element.
type Liability struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CustomerIdHash string                 `protobuf:"bytes,1,opt,name=customer_id_hash,json=customerIdHash,proto3" json:"customer_id_hash,omitempty"` // Poseidon2 hash of the external reference, hex.
	Balance        string                 `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance,omitempty"`                                       // Integer minor units, decimal string.
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Liability) Reset() {
	*x = Liability{}
	mi := &file_prover_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Liability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Liability) ProtoMessage() {}

func (x *Liability) ProtoReflect() protoreflect.Message {
	mi := &file_prover_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Liability.ProtoReflect.Descriptor instead.
func (*Liability) Descriptor() ([]byte, []int) {
	return file_prover_proto_rawDescGZIP(), []int{0}
}

func (x *Liability) GetCustomerIdHash() string {
	if x != nil {
		return x.CustomerIdHash
	}
	return ""
}

func (x *Liability) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

// A single reserve figure attested by a bank or on-chain source.
type Reserve struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	Balance       string                 `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance,omitempty"` // Integer minor units, decimal string.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reserve) Reset() {
	*x = Reserve{}
	mi := &file_prover_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reserve) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reserve) ProtoMessage() {}

func (x *Reserve) ProtoReflect() protoreflect.Message {
	mi := &file_prover_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reserve.ProtoReflect.Descriptor instead.
func (*Reserve) Descriptor() ([]byte, []int) {
	return file_prover_proto_rawDescGZIP(), []int{1}
}

func (x *Reserve) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *Reserve) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

type ProveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reserves      []*Reserve             `protobuf:"bytes,1,rep,name=reserves,proto3" json:"reserves,omitempty"`
	Liabilities   []*Liability           `protobuf:"bytes,2,rep,name=liabilities,proto3" json:"liabilities,omitempty"`
	PrevReserves  string                 `protobuf:"bytes,3,opt,name=prev_reserves,json=prevReserves,proto3" json:"prev_reserves,omitempty"` // Previous cycle total R, for the fraud bound.
	TreeDepth     uint32                 `protobuf:"varint,4,opt,name=tree_depth,json=treeDepth,proto3" json:"tree_depth,omitempty"`         // Fixed depth of the Merkle Sum Tree.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProveRequest) Reset() {
	*x = ProveRequest{}
	mi := &file_prover_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProveRequest) ProtoMessage() {}

func (x *ProveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_prover_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProveRequest.ProtoReflect.Descriptor instead.
func (*ProveRequest) Descriptor() ([]byte, []int) {
	return file_prover_proto_rawDescGZIP(), []int{2}
}

func (x *ProveRequest) GetReserves() []*Reserve {
	if x != nil {
		return x.Reserves
	}
	return nil
}

func (x *ProveRequest) GetLiabilities() []*Liability {
	if x != nil {
		return x.Liabilities
	}
	return nil
}

func (x *ProveRequest) GetPrevReserves() string {
	if x != nil {
		return x.PrevReserves
	}
	return ""
}

func (x *ProveRequest) GetTreeDepth() uint32 {
	if x != nil {
		return x.TreeDepth
	}
	return 0
}

type ProveResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Proof          []byte                 `protobuf:"bytes,1,opt,name=proof,proto3" json:"proof,omitempty"` // Serialized UltraHonk proof.
	PublicInputs   *PublicInputs          `protobuf:"bytes,2,opt,name=public_inputs,json=publicInputs,proto3" json:"public_inputs,omitempty"`
	SerializedTree []byte                 `protobuf:"bytes,3,opt,name=serialized_tree,json=serializedTree,proto3" json:"serialized_tree,omitempty"` // JSON tree for the audit log and inclusion paths.
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProveResponse) Reset() {
	*x = ProveResponse{}
	mi := &file_prover_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProveResponse) ProtoMessage() {}

func (x *ProveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_prover_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProveResponse.ProtoReflect.Descriptor instead.
func (*ProveResponse) Descriptor() ([]byte, []int) {
	return file_prover_proto_rawDescGZIP(), []int{3}
}

func (x *ProveResponse) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *ProveResponse) GetPublicInputs() *PublicInputs {
	if x != nil {
		return x.PublicInputs
	}
	return nil
}

func (x *ProveResponse) GetSerializedTree() []byte {
	if x != nil {
		return x.SerializedTree
	}
	return nil
}

// Values exposed on-chain. Everything else stays private.
type PublicInputs struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ReservesTotal    string                 `protobuf:"bytes,1,opt,name=reserves_total,json=reservesTotal,proto3" json:"reserves_total,omitempty"`          // R
	LiabilitiesTotal string                 `protobuf:"bytes,2,opt,name=liabilities_total,json=liabilitiesTotal,proto3" json:"liabilities_total,omitempty"` // L
	RootHash         string                 `protobuf:"bytes,3,opt,name=root_hash,json=rootHash,proto3" json:"root_hash,omitempty"`                         // root_h, Poseidon2 sum-tree root, hex.
	PrevReserves     string                 `protobuf:"bytes,4,opt,name=prev_reserves,json=prevReserves,proto3" json:"prev_reserves,omitempty"`             // R_prev
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PublicInputs) Reset() {
	*x = PublicInputs{}
	mi := &file_prover_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicInputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicInputs) ProtoMessage() {}

func (x *PublicInputs) ProtoReflect() protoreflect.Message {
	mi := &file_prover_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicInputs.ProtoReflect.Descriptor instead.
func (*PublicInputs) Descriptor() ([]byte, []int) {
	return file_prover_proto_rawDescGZIP(), []int{4}
}

func (x *PublicInputs) GetReservesTotal() string {
	if x != nil {
		return x.ReservesTotal
	}
	return ""
}

func (x *PublicInputs) GetLiabilitiesTotal() string {
	if x != nil {
		return x.LiabilitiesTotal
	}
	return ""
}

func (x *PublicInputs) GetRootHash() string {
	if x != nil {
		return x.RootHash
	}
	return ""
}

func (x *PublicInputs) GetPrevReserves() string {
	if x != nil {
		return x.PrevReserves
	}
	return ""
}

var File_prover_proto protoreflect.FileDescriptor

const file_prover_proto_rawDesc = "" +
	"\n" +
	"\fprover.proto\x12\x0fsolva.prover.v1\"O\n" +
	"\tLiability\x12(\n" +
	"\x10customer_id_hash\x18\x01 \x01(\tR\x0ecustomerIdHash\x12\x18\n" +
	"\abalance\x18\x02 \x01(\tR\abalance\"@\n" +
	"\aReserve\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12\x18\n" +
	"\abalance\x18\x02 \x01(\tR\abalance\"\xc6\x01\n" +
	"\fProveRequest\x124\n" +
	"\breserves\x18\x01 \x03(\v2\x18.solva.prover.v1.ReserveR\breserves\x12<\n" +
	"\vliabilities\x18\x02 \x03(\v2\x1a.solva.prover.v1.LiabilityR\vliabilities\x12#\n" +
	"\rprev_reserves\x18\x03 \x01(\tR\fprevReserves\x12\x1d\n" +
	"\n" +
	"tree_depth\x18\x04 \x01(\rR\ttreeDepth\"\x92\x01\n" +
	"\rProveResponse\x12\x14\n" +
	"\x05proof\x18\x01 \x01(\fR\x05proof\x12B\n" +
	"\rpublic_inputs\x18\x02 \x01(\v2\x1d.solva.prover.v1.PublicInputsR\fpublicInputs\x12'\n" +
	"\x0fserialized_tree\x18\x03 \x01(\fR\x0eserializedTree\"\xa4\x01\n" +
	"\fPublicInputs\x12%\n" +
	"\x0ereserves_total\x18\x01 \x01(\tR\rreservesTotal\x12+\n" +
	"\x11liabilities_total\x18\x02 \x01(\tR\x10liabilitiesTotal\x12\x1b\n" +
	"\troot_hash\x18\x03 \x01(\tR\brootHash\x12#\n" +
	"\rprev_reserves\x18\x04 \x01(\tR\fprevReserves2P\n" +
	"\x06Prover\x12F\n" +
	"\x05Prove\x12\x1d.solva.prover.v1.ProveRequest\x1a\x1e.solva.prover.v1.ProveResponseB`Z^github.com/jes-labs/solva/services/orchestrator/internal/infrastructure/grpc/proverpb;proverpbb\x06proto3"

var (
	file_prover_proto_rawDescOnce sync.Once
	file_prover_proto_rawDescData []byte
)

func file_prover_proto_rawDescGZIP() []byte {
	file_prover_proto_rawDescOnce.Do(func() {
		file_prover_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_prover_proto_rawDesc), len(file_prover_proto_rawDesc)))
	})
	return file_prover_proto_rawDescData
}

var file_prover_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_prover_proto_goTypes = []any{
	(*Liability)(nil),     // 0: solva.prover.v1.Liability
	(*Reserve)(nil),       // 1: solva.prover.v1.Reserve
	(*ProveRequest)(nil),  // 2: solva.prover.v1.ProveRequest
	(*ProveResponse)(nil), // 3: solva.prover.v1.ProveResponse
	(*PublicInputs)(nil),  // 4: solva.prover.v1.PublicInputs
}
var file_prover_proto_depIdxs = []int32{
	1, // 0: solva.prover.v1.ProveRequest.reserves:type_name -> solva.prover.v1.Reserve
	0, // 1: solva.prover.v1.ProveRequest.liabilities:type_name -> solva.prover.v1.Liability
	4, // 2: solva.prover.v1.ProveResponse.public_inputs:type_name -> solva.prover.v1.PublicInputs
	2, // 3: solva.prover.v1.Prover.Prove:input_type -> solva.prover.v1.ProveRequest
	3, // 4: solva.prover.v1.Prover.Prove:output_type -> solva.prover.v1.ProveResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_prover_proto_init() }
func file_prover_proto_init() {
	if File_prover_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_prover_proto_rawDesc), len(file_prover_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_prover_proto_goTypes,
		DependencyIndexes: file_prover_proto_depIdxs,
		MessageInfos:      file_prover_proto_msgTypes,
	}.Build()
	File_prover_proto = out.File
	file_prover_proto_goTypes = nil
	file_prover_proto_depIdxs = nil
}
